apiVersion: v2
name: demo
description: A Helm chart for Kubernetes
# A chart can be either an 'application' or a 'library' chart.
type: application
# This is the chart version. This version number should be incremented each time you make changes
version: 0.0.1
dependencies:
  - name: demo
    version: "0.0.1"
    repository: file://../charts/demo