apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.app_name}}
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.app_name}}
  template:
    metadata:
      labels:
        app: {{.Values.app_name}}
    spec:
      containers:
        - name: {{.Values.image.repository}}
          image: {{.Values.image.repository}}
          ports:
            - containerPort: 80
          imagePullPolicy: {{.Values.image.pullPolicy}}
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "50Mi"
              cpu: "50m"
      restartPolicy: Always